import type { Pin } from "./types";

export const SEED_PINS: Omit<Pin, "id">[] = [
  {
    title: "Memorial Church mosaics",
    type: "guided",
    era: "1900s",
    lat: 37.4275,
    lng: -122.1711,
    contributor: { name: "Prof. Elena Voss", role: "Historian" },
    tags: ["Mission Revival", "Stanford founding", "Religious architecture"],
    upvotes: { accurate: 18, helpful: 43 },
    annotations: [
      { x: 50, y: 22, note: "Look at the mosaic above the entrance. Notice how the gold tessera on the left seems brighter?", question: "Why might one section look newer than the rest?" },
      { x: 30, y: 65, note: "The sandstone facade uses a warm buff color typical of Mission Revival style.", question: "Can you spot where earthquake repairs used a slightly different stone?" },
      { x: 75, y: 80, note: "The cornerstone reads 1903 — but Stanford was founded in 1891.", question: "What happened between 1891 and 1903 that required rebuilding?" },
    ],
    description: "Stanford Memorial Church is one of the most visited buildings on campus, but most people walk past without noticing the layers of rebuilding visible in its stone.",
    resources: [
      { label: "Stanford Archives — Church collection", type: "archive" },
      { label: "Mission Revival Architecture in California (book)", type: "book" },
    ],
    createdAt: new Date(),
  },
  {
    title: "The Cactus Garden's hidden origin",
    type: "story",
    era: "1880s",
    lat: 37.4265,
    lng: -122.1735,
    contributor: { name: "Maria Santos", role: "Local" },
    tags: ["Landscape architecture", "Stanford founding", "Leland Stanford Jr."],
    upvotes: { accurate: 7, helpful: 22 },
    annotations: [],
    description: "Most people think the Cactus Garden is just decorative. But it was originally planted by Leland Stanford himself, who had a fascination with desert botany after trips through Arizona Territory. The garden predates the university.",
    resources: [],
    createdAt: new Date(),
  },
  {
    title: "Where the oak grove stood",
    type: "memory",
    era: "1970s",
    lat: 37.4255,
    lng: -122.169,
    contributor: { name: "James Whitfield", role: "Alumnus" },
    tags: ["Campus life", "Environmental history", "Student activism"],
    upvotes: { accurate: 4, helpful: 15 },
    annotations: [],
    description: "There used to be a massive oak grove right here — I remember studying under those trees in '74. They were cut down for the science building expansion. There was a student protest, but it didn't save them. If you look at the ground carefully near the east wall, you can still see where two stumps were paved over.",
    resources: [],
    createdAt: new Date(),
  },
  {
    title: "What is this symbol?",
    type: "request",
    era: null,
    lat: 37.428,
    lng: -122.17,
    contributor: { name: "Traveling_Soph", role: "Explorer" },
    tags: [],
    upvotes: { accurate: 0, helpful: 3 },
    annotations: [
      { x: 48, y: 52, note: "I found this carved into the base of a lamp post near the quad. It looks like intertwined letters but I can't make them out.", question: null },
    ],
    description: "Found this while walking around the Main Quad. Anyone know what it means?",
    resources: [],
    createdAt: new Date(),
  },
  {
    title: "Rodin sculpture garden — the casting debate",
    type: "guided",
    era: "1980s",
    lat: 37.4322,
    lng: -122.1642,
    contributor: { name: "Art History Society", role: "Organisation" },
    tags: ["Public art", "Rodin", "Bronze casting", "Museum collections"],
    upvotes: { accurate: 12, helpful: 31 },
    annotations: [
      { x: 35, y: 40, note: "This is a posthumous cast of The Burghers of Calais. Rodin died in 1917 — this was cast in the 1980s.", question: "If a sculpture is cast after the artist's death from the original molds, is it still 'a Rodin'? What makes art authentic?" },
      { x: 65, y: 70, note: "Run your hand along the base (gently). The patina here is different from older casts in Paris.", question: "What does the surface texture tell you about the age of a bronze?" },
    ],
    description: "Stanford's Rodin collection is one of the largest outside Paris, but almost all of it was cast decades after Rodin's death. This raises fascinating questions about authenticity in art.",
    resources: [
      { label: "Cantor Arts Center — free admission", type: "museum" },
      { label: "Rodin casting history (Stanford exhibit guide)", type: "guide" },
    ],
    createdAt: new Date(),
  },
];
